### PR TITLE
Configuration Management Overrides for Cinder

### PR DESCRIPTION
**Pull request by dulek**
**What is the purpose of this pull request?**:

This commit is based on how Nova got its configuration overrides
implemented.

An important thing here is support for setting multiple Cinder backends
(e.g. Ceph cluster + NFS) in the values.yaml.

**What issue does this pull request address?**:

**Notes for reviewers to consider**:

**Specific reviewers for pull request**:
@v1k0d3n @alanmeadows

### CODE REVIEW

**Comment by intlabs** [comment]
@dulek could you please rebase this against the current master?

**Comment by dulek** [comment]
@intlabs: Sure thing, I'm on it. My bad I haven't checked for conflicts before pushing.

**Comment by dulek** [comment]
Just FYI - it's rebased now. :)

**Comment by v1k0d3n** [comment]
@dulek you just missed the openstack merge cutoff. the project has moved into openstack officially. reach out to us over IRC and we can coordinate getting this in there.

https://github.com/att-comdev/openstack-helm

**Comment by v1k0d3n** [comment]
closing this PR in favor of moving the work to Openstack proper: https://github.com/openstack/openstack-helm

**Pull request closed without merging**
