### PR TITLE
Resolves issue #149

### PR DESCRIPTION
**Pull request by alraddarla**
This change is [Reviewable](https://reviewable.io/reviews/att-comdev/openstack-helm/150)

### CODE REVIEW

**Comment by alraddarla** [comment]
Resolves typo in common chart #149

**Comment by intlabs** [comment]
@alraddarla, unfortunately this change needs to be reflected in all the charts which reference it, eg:

* https://github.com/att-comdev/openstack-helm/blob/92512d66bb45d078775c92d324dbedb85a686536/neutron/templates/etc/_ml2-conf.ini.tpl#L3
* https://github.com/att-comdev/openstack-helm/blob/c000c23b1db02007675e34b6a8042387e811efe5/common/templates/snippets/_k8s_init_dep_check.tpl#L33
* https://github.com/att-comdev/openstack-helm/blob/bab88b829ea29c68852b9153c4d5630db17704a1/cinder/templates/etc/_cinder.conf.tpl#L18

And possibly some others. A find&replace through the repo should fix it - but we should get confirmation that every instance is changed before merging.

**Comment by v1k0d3n** [comment]
@intlabs to be fair...you did mention only common :)

**Comment by intlabs** [comment]
@v1k0d3n sorry :(

**Comment by v1k0d3n** [comment]
@intlabs no worries. easy oversight for a new contributor to make. @alraddarla, as long as you still have your fork, we can work through this tomorrow. it's straight forward with GitHub...you just do the same thing you already did (clone, fix, commit, push), and it GitHub will automatically update this open Pull Request.

**Comment by alraddarla** [comment]
New changes pushed for #149

**Comment by intlabs** [comment]
@alraddarla @v1k0d3n Looks awesome! Thanks for sorting this :)

**Comment by larryrensing** [comment]
looks good to me, i'll have to rebase my PR on top of yours if yours gets merged in first

https://github.com/att-comdev/openstack-helm/pull/148/files#diff-6c64e390181021848b045240a0e4858aR49

**Pull request merged**
