### PR TITLE
Cleanup for Keystone Endpoint Lookup refactor

### PR DESCRIPTION
**Pull request by intlabs**
**What is the purpose of this pull request?**: To remove orphan Keystone endpoint lookups and functions from helm-toolkit

**What issue does this pull request address?**: Supersedes https://github.com/att-comdev/openstack-helm/pull/208

This PR removes the Keystone endpoint lookups and functions from Helm-Toolkit that have been orphaned by unifying the way this is implemented across all charts.

**Notes for reviewers to consider**:
This PR should only be considered for merging after the following PR's have been merged:
 - https://github.com/att-comdev/openstack-helm/pull/249
 - https://github.com/att-comdev/openstack-helm/pull/250
 - https://github.com/att-comdev/openstack-helm/pull/251
 - https://github.com/att-comdev/openstack-helm/pull/252

**Specific reviewers for pull request**: @alanmeadows @v1k0d3n @larryrensing @wilkers-steve

### CODE REVIEW

**Comment by intlabs** [comment]
The failure of Travis is expected until the required PRs have merged.

**Comment by wilkers-steve** [comment]
This LGTM.  Thanks for working this, @intlabs

**Comment by v1k0d3n** [comment]
ah, thanks for the review @wilkers-steve

**Comment by wilkers-steve** [comment]
We can close this one out

**Pull request merged**
