### PR TITLE
feat: Horizon Add development setting, exposing the service via a NodePort.

### PR DESCRIPTION
**Pull request by intlabs**
This commit adds a `development` option similar to MariaDB. It simply exposes Horizon using a NodePort@31537/tcp to make is a bit more user-friendly to get going in Minikube.

---
This change is [Reviewable](https://reviewable.io/reviews/att-comdev/openstack-helm/111)

### CODE REVIEW

**Comment by v1k0d3n** [comment]
@intlabs these are good changes that we'd like to see. if you have a moment to refactor, i'll pull them in.

**Comment by v1k0d3n** [comment]
this got left out on an island, and there is an issue/PR that will supersede this PR. in fact #258 should've referenced this previous work. @intlabs what are your thoughts? i'll leave it up to you, and you can coordinate with @wilkers-steve on what you guys are deciding to do here.

**Comment by wilkers-steve** [comment]
@v1k0d3n the approach for nodeports proposed in PR #261 conflicts with how it's handled for Horizon here. I'm a fan of using the approach in #261 because it doesn't tie nodeports directly to development mode. If we want that to be the case, we should address it in the node port PR and propose a tree structure that would scope them under development.

**Comment by v1k0d3n** [comment]
@wilkers-steve of course...this was just a quick PR to address having horizon exposed for development. i just don't like closing peoples PR's without getting their feedback first. ;)

**Comment by intlabs** [comment]
This has been superseded a number of times, by various methods ;) I'm good with closing this, cheers @v1k0d3n

**Pull request closed without merging**
