### PR TITLE
Bugfix a few typos from last three PRs

### PR DESCRIPTION
**Pull request by alanmeadows**
This resolves a few issues that crept in with the last
three pull requests.

---
This change is [Reviewable](https://reviewable.io/reviews/att-comdev/openstack-helm/85)

### CODE REVIEW

**Comment by wilkers-steve** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Makefile, line 1 at r1](https://reviewable.io:443/reviews/att-comdev/openstack-helm/85#-K_aw79FZX7MbZ0l3ONY:-K_aw79FZX7MbZ0l3ONZ:b-vqa20e) ([raw file](https://github.com/att-comdev/openstack-helm/blob/f9cb3fc8461cf6506ac03e85e07b19774267933d/Makefile#L1)):*
> ```Makefile
> .PHONY: ceph bootstrap mariadb keystone memcached rabbitmq common openstack neutron all clean
> ```

Do we need a phony target for nova?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/att-comdev/openstack-helm/85)*

**Comment by alanmeadows** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Makefile, line 1 at r1](https://reviewable.io:443/reviews/att-comdev/openstack-helm/85#-K_aw79FZX7MbZ0l3ONY:-K_axNxpcyrA5jyk18UJ:b-yyp1rl) ([raw file](https://github.com/att-comdev/openstack-helm/blob/f9cb3fc8461cf6506ac03e85e07b19774267933d/Makefile#L1)):*
<details><summary><i>Previously, wilkers-steve wrote…</i></summary><blockquote>

Do we need a phony target for nova?
</blockquote></details>

The pull request for that is still out standing, so we do not just yet!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/att-comdev/openstack-helm/85)*

**Comment by wilkers-steve** [comment]
Oh hah.  That would make sense. :+1:

**Comment by alanmeadows** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Makefile, line 1 at r1](https://reviewable.io:443/reviews/att-comdev/openstack-helm/85#-K_aw79FZX7MbZ0l3ONY:-K_axwLikXL54LSRMdXI:b-46tlek) ([raw file](https://github.com/att-comdev/openstack-helm/blob/f9cb3fc8461cf6506ac03e85e07b19774267933d/Makefile#L1)):*
<details><summary><i>Previously, alanmeadows (Alan Meadows) wrote…</i></summary><blockquote>

The pull request for that is still out standing, so we do not just yet!
</blockquote></details>

Removed all references of it for now--nice catch Steve.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/att-comdev/openstack-helm/85)*

**Comment by v1k0d3n** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/att-comdev/openstack-helm/85#-:-K_bAQVgUYPPbsai4Zn6:bnfp4nl)*

**Pull request merged**
