### PR TITLE
minikube.md proofreading

### PR DESCRIPTION
**Pull request by mattmceuen**
The Minikube getting started guide is really excellent, and worked flawlessly for this Minikube newbie!  I caught a few proofreading nits along the way.

---
This change is [Reviewable](https://reviewable.io/reviews/att-comdev/openstack-helm/86)

### CODE REVIEW

**Comment by wilkers-steve** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/developer/minikube.md, line 116 at r1](https://reviewable.io:443/reviews/att-comdev/openstack-helm/86#-K_awgdf8D-g0TlHT-g8:-K_awgdf8D-g0TlHT-g9:bgfghx0) ([raw file](https://github.com/att-comdev/openstack-helm/blob/c93eea00ae9fb6d674b3e9606d72668debae6492/docs/developer/minikube.md#L116)):*
> wtih
Could you fix this too? :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/att-comdev/openstack-helm/86)*

**Comment by v1k0d3n** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/developer/minikube.md, line 78 at r1](https://reviewable.io:443/reviews/att-comdev/openstack-helm/86#-K_b9GcwqeZqgyDzujAb:-K_b9GcwqeZqgyDzujAc:beal6fq) ([raw file](https://github.com/att-comdev/openstack-helm/blob/a641c113cb0b3da4610de09431b396ec3fcbf8ce/docs/developer/minikube.md#L78)):*
> helm serve . &

man, this is pretty picky :) both are correct.

---

*[docs/developer/minikube.md, line 116 at r1](https://reviewable.io:443/reviews/att-comdev/openstack-helm/86#-K_awgdf8D-g0TlHT-g8:-K_b9ATwznllpsGNh6AH:burx042) ([raw file](https://github.com/att-comdev/openstack-helm/blob/c93eea00ae9fb6d674b3e9606d72668debae6492/docs/developer/minikube.md#L116)):*
<details><summary><i>Previously, wilkers-steve wrote…</i></summary><blockquote>

> wtih
Could you fix this too? :)
</blockquote></details>

good catch :)

---

*[docs/developer/minikube.md, line 170 at r1](https://reviewable.io:443/reviews/att-comdev/openstack-helm/86#-K_b8nf75hWxQx0BRHxK:-K_b8nf75hWxQx0BRHxL:bm8v6a0) ([raw file](https://github.com/att-comdev/openstack-helm/blob/c93eea00ae9fb6d674b3e9606d72668debae6492/docs/developer/minikube.md#L170)):*
> of the 

perhaps remove "of the" also to say "After each chart is deployed".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/att-comdev/openstack-helm/86)*

**Comment by mattmceuen** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/developer/minikube.md, line 78 at r1](https://reviewable.io:443/reviews/att-comdev/openstack-helm/86#-K_b9GcwqeZqgyDzujAb:-K_bZXWo1lZocKzOiD3i:bdzi2ze) ([raw file](https://github.com/att-comdev/openstack-helm/blob/a641c113cb0b3da4610de09431b396ec3fcbf8ce/docs/developer/minikube.md#L78)):*
<details><summary><i>Previously, v1k0d3n (Brandon B. Jozsa) wrote…</i></summary><blockquote>

> helm serve . &

man, this is pretty picky :) both are correct.
</blockquote></details>

Oh if that's the case, I will retract.  "helm serve --help" didn't mention it and the helm/serve.go source appeared to ignore it, so I thought maybe it was a typo.

---

*[docs/developer/minikube.md, line 116 at r1](https://reviewable.io:443/reviews/att-comdev/openstack-helm/86#-K_awgdf8D-g0TlHT-g8:-K_bZrzX6MA4GaMM7UAC:bvh13uo) ([raw file](https://github.com/att-comdev/openstack-helm/blob/c93eea00ae9fb6d674b3e9606d72668debae6492/docs/developer/minikube.md#L116)):*
<details><summary><i>Previously, v1k0d3n (Brandon B. Jozsa) wrote…</i></summary><blockquote>

good catch :)
</blockquote></details>

Haha, will do.

---

*[docs/developer/minikube.md, line 170 at r1](https://reviewable.io:443/reviews/att-comdev/openstack-helm/86#-K_b8nf75hWxQx0BRHxK:-K_b_6p_pfJm2c-IMEAX:bie756y) ([raw file](https://github.com/att-comdev/openstack-helm/blob/c93eea00ae9fb6d674b3e9606d72668debae6492/docs/developer/minikube.md#L170)):*
<details><summary><i>Previously, v1k0d3n (Brandon B. Jozsa) wrote…</i></summary><blockquote>

> of the 

perhaps remove "of the" also to say "After each chart is deployed".
</blockquote></details>

Yeah, that's a good call, will do.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/att-comdev/openstack-helm/86)*

**Comment by intlabs** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/developer/minikube.md, line 78 at r1](https://reviewable.io:443/reviews/att-comdev/openstack-helm/86#-K_b9GcwqeZqgyDzujAb:-K_im91gA7lilZToYYns:b-10l5uk) ([raw file](https://github.com/att-comdev/openstack-helm/blob/a641c113cb0b3da4610de09431b396ec3fcbf8ce/docs/developer/minikube.md#L78)):*
<details><summary><i>Previously, mattmceuen wrote…</i></summary><blockquote>

Oh if that's the case, I will retract.  "helm serve --help" didn't mention it and the helm/serve.go source appeared to ignore it, so I thought maybe it was a typo.
</blockquote></details>

@v1k0d3n, I'm with Matt on this. Though it works no problems - like him I scurries off to find out what the `.` did  - as I wondered if it was going to serve from the current directory or similar. Made me actually RTFM though so that's a bonus! :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/att-comdev/openstack-helm/86)*

**Comment by v1k0d3n** [comment]
@intlabs find to remove. either way works for me. @mattmceuen you should be able to update those changes and commit them back, and it will automatically update this PR. then we can merge in.

**Comment by wilkers-steve** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/developer/minikube.md, line 116 at r2](https://reviewable.io:443/reviews/att-comdev/openstack-helm/86#-K_oJxgd61_43bbL1BHI:-K_oJxgd61_43bbL1BHJ:b-b8oero) ([raw file](https://github.com/att-comdev/openstack-helm/blob/4cef79295ab07bec433b2a602510508e2fdc00d6/docs/developer/minikube.md#L116)):*
> ```Markdown
> * Persistent Storage used for Minikube development mode is `hostPath`. The Ceph PVC's included with this project are not intended to work with Minikube.
> * There is *no need* to install the `common` `ceph` or `bootstrap` charts. These charts are required for deploying Ceph PVC's.
> * Familiarize yourself with `values.yaml` included wtih the MariaDB chart. You will want to have the `hostPath` directory created prior to deploying MariaDB.
> ```

Looks like another 'wtih' snucky by me on that line, after 'included'.  Sorry Matt

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/att-comdev/openstack-helm/86)*

**Comment by v1k0d3n** [comment]
LGTM. thanks @mattmceuen

**Pull request merged**
